---
title: "ClinTrialPredidct"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ClinTrialPredidct}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ClinTrialPredict)
```


This is test.

```{=latex}
\begin{table}[ht]
        \centering
        \caption{calculate l}
        \begin{tabular}{rrrrrrrrrr}
          \hline
         & m & s & alpha0.t & nu0.t & HR & gamma.c & d & l & meanD \\ 
          \hline
        1 & 6.00 & 12.00 & 0.80 & 20.00 & 0.80 & 0.10 & 20.00 & 4.18 & 20.10 \\ 
          2 & 6.00 & 12.00 & 0.80 & 20.00 & 0.80 & 0.10 & 50.00 & 7.56 & 50.00 \\ 
          3 & 6.00 & 12.00 & 0.80 & 20.00 & 0.80 & 0.10 & 100.00 & 13.28 & 100.10 \\ 
          4 & 18.00 & 12.00 & 1.20 & 20.00 & 1.20 & 0.10 & 20.00 & 7.00 & 20.10 \\ 
          5 & 18.00 & 12.00 & 1.20 & 20.00 & 1.20 & 0.10 & 50.00 & 11.63 & 50.00 \\ 
          6 & 18.00 & 12.00 & 1.20 & 20.00 & 1.20 & 0.10 & 100.00 & 22.79 & 100.10 \\ 
           \hline
        \end{tabular}
\end{table}
```



